const express = require('express')
const cors = require('cors')
require('./db/mongoose')
const userRoutes = require('./routes/users')
const bookRoutes = require('./routes/book')
const app = express()
app.use(cors())
const port = process.env.PORT || 3000
app.use(express.json())
app.use(userRoutes)
app.use(bookRoutes)
app.listen(port)